"name": "Urial WildSheep",
    "website": "https://urialwildsheep.com",
    "description": "Urial WildSheep is a new crypto issued by URIAL Team To protect the environment and introduce solutions to the whole world.",
    "explorer": "https://bscscan.com/token/0xaac67495301ba344b5458024ee366a12b65b4600",
    "type": "BEP20",
    "symbol": "URIAL",
    "decimals": 18,
    "status": "active",
    "id": "0xaac67495301ba344b5458024ee366a12b65b4600"
     Urial WildSheep

     URIAL

     0xAAc67495301Ba344B5458024EE366a12b65B4600

     18

     Time Series: Token Contract Overview

     Mon 7, Feb 2022 
